INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'ASP.NET Core MVC с примерами на C# для профессионалов', N'В книге объясняется, как эффективно применять новые возможности инфраструктуры "модель-представление-контроллер" (MVC), обновленной до версии ASP.NET Core MVC. Теперь вы сможете создавать более экономные, оптимизированные под облако и готовые к функционированию на мобильных устройствах приложения для платформы .NET. Книга предоставляет детальное описание того, как вписать новую функциональность в существующий контекст разработки.', CAST(3000.00 AS Decimal(16, 2)), NULL, NULL, 2, 1, N'/Content/images/Pro AspNet Core MVC.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'ASP.NET MVC 5 Framework с примерами на C#', N'ASP.NET MVC 3 Framework представляет собой последнюю версию веб-платформы ASP.NET от Microsoft. Она предлагает высокопроизводительную модель программирования, которая способствует построению более чистой кодовой архитектуры, обеспечивает разработку, управляемую тестами, и позволяет повсеместную расширяемость в комбинации со всеми преимуществами версии ASP.NET 4.', CAST(3700.00 AS Decimal(16, 2)), NULL, NULL, 2, 1, N'/Content/images/Pro ASP.NET MVC 5.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'ASP.NET MVC 5 - Построение сайта с использованием Visual Studio 2015 и C Sharp: Тактическая книга', N'Изучите актуальные вопросы безопасности и развертывания, включая особенности использования IIS 7
Эта книга предназначена для разработчиков веб-приложений, имеющих базовые знания ASP.NET и C#, которые желают (или нуждаются) в переходе к использованию новой платформы ASP.NET MVC 5 Framework. ', CAST(4200.00 AS Decimal(16, 2)), NULL, NULL, 2, 1, N'/Content/images/ASP.NET MVC 5 - Building a Website with Visual Studio 2015 and C Sharp.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Построение динамичных, мобильных приложений на ASP.NET MVC 5', N'Платформа ASP.NET Core MVC предлагает "независимую от хоста" инфраструктуру и высокопродуктивную модель программирования, которая способствует построению более чистой кодовой архитектуры, разработке через тестирование и значительной расширяемости.', CAST(3900.00 AS Decimal(16, 2)), NULL, NULL, 2, 1, N'/Content/images/ASP.NET MVC 5 with Bootstrap and Knockout.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Профессиональная разработка в ASP.NET MVC 5', N'Он представляет полностью работающий учебный пример функционирующего приложения ASP.NET MVC, который вы сможете использовать в качестве шаблона для собственных проектов. Вы начнете с азов и постепенно доберетесь до описания более сложных средств.', CAST(5500.00 AS Decimal(16, 2)), NULL, NULL, 2, 1, N'/Content/images/Professional ASP.NET MVC 5.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Язык программирования C# 6.0 и платформа .NET 4.6', N'овое 7-е издание этой книги было полностью пересмотрено и переписано с учетом последних изменений спецификации языка C# и новых достижений платформы .NET Framework. Отдельные главы посвящены важным новым средствам, которые делают .NET Framework 4.6 самым передовым выпуском', CAST(4500.00 AS Decimal(16, 2)), NULL, NULL, 1, 1, N'/Content/images/C Sh 6.0 and the .NET 4.6 Framework.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'C# для профессионалов. Тонкости программирования', N'Книга C# ДЛЯ ПРОФЕССИОНАЛОВ. ТОНКОСТИ ПРОГРАММИРОВАНИЯ (C# in Depth) является обновлением предыдущего издания, ставшего бестселлером, с целью раскрытия новых средств языка C# 5, включая решение проблем, которые связаны с написанием сопровождаемого асинхронного кода.', CAST(4200.00 AS Decimal(16, 2)), NULL, NULL, 1, 1, N'/Content/images/C Sh in Depth, 3rd Edition.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Эффективная разработка на C# (Включая C# 6.0)', N'Помимо этого предлагается исчерпывающее рассмотрение всех ключевых возможностей языка C#, как старых, так и новых, что позволило обрести популярность предыдущим изданиям этой книги. Читатели получат основательные знания приемов объектно-ориентированной обработки, атрибутов и рефлексии, обобщений и коллекций.', CAST(4700.00 AS Decimal(16, 2)), NULL, NULL, 1, 1, N'/Content/images/Effective C Sh (Covers CSh 6.0).jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'C# 6.0. Справочник. Полное описание языка', N'Данное руководство, ставшее бестселлером, позволяет получить точные ответы практически на любые вопросы по C# 6.0, CLR и основным сборкам .NET Framework. После своего появления в 2000 году C# стал языком с выдающейся гибкостью и мощью, но его постоянный рост и совершенствование означают необходимость в дополнительном изучении.', CAST(4500.00 AS Decimal(16, 2)), NULL, NULL, 1, 1, N'/Content/images/C Sh 6.0 in a Nutshell The Definitive Reference.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'C# 6 для программистов (6th Издание) ( Дейтель)', N'Основная миссия книги заключается в том, чтобы служить исчерпывающим руководством по языку программирования C# и ключевым аспектам платформы .NET, а также предоставлять обзорные сведения о технологиях, построенных на основе C# и .NET (ADO.NET и Entity Framework, Windows Communication Foundation (WCF), Windows Presentation Foundation (WPF) и ASP.NET (Web Forms, MVC, Web API)).', CAST(3500.00 AS Decimal(16, 2)), NULL, NULL, 1, 1, N'/Content/images/C Sh 6 for Programmers (6th Edition) (Deitel Developer Series).jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Изучаем ASP.Net MVC - Обучающий ДВД', N'Изучите все аспекты языка C#, начиная с основ синтаксиса и переменных и заканчивая сложными темами, такими как указатели и перегрузка операций.
Научитесь пользоваться языком LINQ благодаря трем посвященным ему главам. 
Освойте динамическое, асинхронное и параллельное программирование. ', CAST(3000.00 AS Decimal(16, 2)), NULL, NULL, 2, 2, N'/Content/images/Learning ASP.Net MVC - Training DVD.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Программирование на  C# - Подготовка к экзамену 70-483', N'Получите навыки работы со средствами .NET, в числе которых XML, взаимодействие с сетью, сериализация, рефлексия, безопасность, домены приложений и контракты кода. 
Исследуйте новый компилятор как службу C# 6.0 под названием Roslyn. ', CAST(4700.00 AS Decimal(16, 2)), NULL, NULL, 1, 2, N'/Content/images/Programming in Microsoft CSh - Exam 70-483 - Training DVD.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Изучаем C# лучшие практики - Обучающий ДВД.jpg', N'Помимо этого предлагается исчерпывающее рассмотрение всех ключевых возможностей языка C#, как старых, так и новых, что позволило обрести популярность предыдущим изданиям этой книги. Слушатели получат основательные знания приемов объектно-ориентированной обработки, атрибутов и рефлексии, обобщений и коллекций, а также обретут понимание многих сложных тем, которые не раскрываются в других источниках (таких как коды операций CIL и выпуск динамических сборок).', CAST(5100.00 AS Decimal(16, 2)), NULL, NULL, 1, 2, N'/Content/images/Learning CSh Best Practices - Training DVD.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'ASP.NET MVC 4 Основной курс', N'Усовершенствованная модель программирования ADO.NET Entity Framework; 
- Многочисленные улучшения IDE-среды и архитектуры MVVM для разработки настольных приложений WPF;
- Многочисленные обновления в ASP.NET Web API.', CAST(5300.00 AS Decimal(16, 2)), NULL, NULL, 1, 2, N'/Content/images/ASP.NET MVC 4 Essential Training.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'Изучаем программирование на JavaScript  - обучающий DVD', N'С помощью этго курса вы узнаете все о языке JavaScript - от переменных до циклов. Вы поймете, почему разные браузеры по-разному реагируют на код и как написать универсальный код, поддерживаемый всеми браузерами. Вам станет ясно, почему с кодом JavaScript никогда не придется беспокоиться о перегруженности страниц и ошибках передачи данных.', CAST(5300.00 AS Decimal(16, 2)), NULL, NULL, 3, 2, N'/Content/images/Learning JavaScript Programming - Training DVD.jpg')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'70-480 - MSCert:Programming in HTML5 with JavaScript and CSS3', N'Study for your Microsoft 70-480 Certification Exam with the tools that fit your preferred study method. Transcender offers individual study tools, such as a Practice Exam and Skillsoft elearning to give you more options. Select your preferred study method with the drop-down menu to the right.', CAST(9000.00 AS Decimal(16, 2)), NULL, NULL, 3, 3, N'/Content/images/cert-70-480.png')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'70-483 - MSCert: Programming in C#', N'Study for your Microsoft 70-483 Certification Exam with the tools that fit your preferred study method. Transcender offers individual study tools, such as a Practice Exam and Skillsoft elearning to give you more options. Select your preferred study method with the drop-down menu to the right.', CAST(5500.00 AS Decimal(16, 2)), NULL, NULL, 1, 3, N'/Content/images/cert-70-483.png')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'70-486 - MSCert: Developing ASP.NET MVC Web Applications', N'Study for your Microsoft 70-486 Certification Exam with the tools that fit your preferred study method. Transcender offers individual study tools, such as a Practice Exam and Skillsoft elearning to give you more options. Select your preferred study method with the drop-down menu to the right.', CAST(8500.00 AS Decimal(16, 2)), NULL, NULL, 1, 3, N'/Content/images/cert-70-486.png')
INSERT INTO [dbo].[Products] ( [Name], [Description], [Price], [ImageData], [ImageMimeType], [CategoryId], [TypeId], [ImageUrl]) VALUES ( N'70-487 - MSCert: Developing Microsoft Azure and Web Services', N'Study for your Microsoft 70-487 Certification Exam with the tools that fit your preferred study method. Transcender offers individual study tools, such as a Practice Exam and Skillsoft elearning to give you more options. Select your preferred study method with the drop-down menu to the right.', CAST(9500.00 AS Decimal(16, 2)), NULL, NULL, 1, 3, N'/Content/images/cert-70-487.png')
