SET IDENTITY_INSERT [DB_A1A80E_eugenedia1].[dbo].[Products] ON
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (1, N'Kayak', N'A boat for one person', N'Watersports', CAST(230.00 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (2, N'Lifejacket', N'Protective and fashionable', N'Watersports', CAST(48.95 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (3, N'Soccer Ball', N'FIFA-approved size and weight 12', N'Soccer', CAST(19.50 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (4, N'Corner Flags', N'Give your playing field a professional touch ', N'Soccer', CAST(34.95 AS Decimal(16, 2)),NULL, N'image/jpeg')
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (5, N'Stadium', N'Flat-packed 35,000-seat stadium', N'Soccer', CAST(79500.00 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (6, N'Thinking Cap', N'Improve your brain efficiency by 75%', N'Chess', CAST(16.00 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (7, N'Unsteady Chair', N'Secretly give your opponent a disadvantage', N'Chess', CAST(29.95 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (8, N'Human Chess Board', N'A fun game for the family', N'Chess', CAST(75.00 AS Decimal(16, 2)), NULL, NULL)
INSERT INTO [DB_A1A80E_eugenedia1].[dbo].[Products] ([ProductID], [Name], [Description], [Category], [Price], [ImageData], [ImageMimeType]) VALUES (9, N'Bling-Bling King', N'Gold-plated, diamond-studded King', N'Chess', CAST(1200.00 AS Decimal(16, 2)), NULL, NULL)
SET IDENTITY_INSERT [DB_A1A80E_eugenedia1].[dbo].[Products] OFF
